services:

  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 8080:8080
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    depends_on:
      - backend
    networks:
      - react-express
    expose:
      - 8080

  backend:
    build:
      context: backend
      target: development
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    depends_on:
      - mongo
    networks:
      - express-mongo
      - react-express
    expose: 
      - 3000

  mongo:
    restart: always
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - express-mongo
    expose:
      - 27017

networks:
  react-express:
  express-mongo: